on:
  workflow_dispatch:
    inputs:
      token:
        type: string
        description: AWS Session Token
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  dryRun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mask token
        run: |
          AWS_TOKEN=$(jq -r '.inputs.token' $GITHUB_EVENT_PATH)
          echo ::add-mask::$AWS_TOKEN
          echo AWS_TOKEN=$AWS_TOKEN >> $GITHUB_ENV
      - name: Calculating changes
        run: |
          echo "Calculating changes ${{ env.AWS_TOKEN }}"
          cat dryRun.md >> $GITHUB_STEP_SUMMARY

  deploy:
    needs: dryRun
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mask token
        run: |
          AWS_TOKEN=$(jq -r '.inputs.token' $GITHUB_EVENT_PATH)
          echo ::add-mask::$AWS_TOKEN
          echo AWS_TOKEN=$AWS_TOKEN >> $GITHUB_ENV
      - name: Deploy
        run: echo "Deploying to production ${{ env.AWS_TOKEN }}"
      - name: Posting deployment summary
        run: echo '### Deployment complete! 🚀' >> $GITHUB_STEP_SUMMARY
