on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  dryRun:
    runs-on:
      labels: ubuntu-latest
    steps:
      - run: |
          echo '### Looks good! 🚀' >> $GITHUB_STEP_SUMMARY

  deploy:
    needs: dryRun
    runs-on:
      labels: ubuntu-latest
    environment: production
    steps:
      - run: |
          echo 'deploying to production'
